[package]
name = "rust_factorial"
version = "0.1.0"
authors = ["Alexis Gallagher <alexis@alexisgallagher.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
